#!/bin/bash
# -----------------------------------------------------------------------------
# @file bash-local
#
# @brief This script acts as an entry-point for bash-local.
# @description It is sourced when a new terminal session starts. Sources the
# `cd` hook and the CLI, as well as the internal core API and the context
# definition.

# Source files
source "$(dirname "${BASH_SOURCE[0]}")/lib/context.sh"
source "$(dirname "${BASH_SOURCE[0]}")/lib/core.sh"
source "$(dirname "${BASH_SOURCE[0]}")/lib/hook.sh"
source "$(dirname "${BASH_SOURCE[0]}")/lib/cli.sh"